name: CI - dbt Airflow Project

permissions:
    contents: read
    packages: write

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Check Airflow DAG syntax
        run: |
          python -m py_compile airflow/dags/*.py  


      - name: Install dbt dependencies
        run: |
          pip install dbt-core==1.9.4 dbt-snowflake==1.9.4

      - name: Run dbt debug


       # run: |
        working-directory: ./netproject
        run: dbt debug --profiles-dir ../.dbt  


      - name: Run dbt dependencies
        working-directory: ./netproject
        run: dbt deps --profiles-dir ../.dbt

      - name: Run dbt tests
        working-directory: ./netproject
        run: dbt test --profiles-dir ../.dbt  

      - name: Build Docker images
        run: docker compose build


  deploy:
  needs: build 

  runs-on: ubuntu-latest
      

  steps:

    - name: Checkout repository 
      uses: actions/checkout@v4 

    - name: Log in to GitHub Container Registry 
      uses: docker/login-action@v3   

      with: 
        registry: ghcr.io 
        username: ${{ github.actor }} 
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Airflow image 
      uses: docker/build-push-action@v6 
      with:    
        context: . 
        file: ./airflow/Dockerfile 
        push: true 
        tags: ghcr.io/${{ github.repository_owner }}/dbt-airflow:latest