name: CI - dbt Airflow Project

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      - name: Check Airflow DAG syntax
        run: |
          python -m py_compile airflow/dags/*.py  